### ISSUE TITLE
Zinnia breaks on Django 1.7b1: get_user_model at init time

### ISSUE THREAD

**Issue by delroth** [Fantomas42/django-blog-zinnia#342]
zinnia.models.author.Author uses get_user_model() at module import time, which is forbidden by Django 1.7 (https://docs.djangoproject.com/en/dev/releases/1.7/#app-loading-refactor). 1.7 is due for release soon (beta has been released), so a way to avoid this import time dependency should be figured out.

**Comment by faraggi** [comment]
I am getting the same or similar error on python 3.4.0 django 1.7.5.
This is the output of migrate:

    (project)username@computername:~/project/application$ python manage.py migrate
    Operations to perform:
      Synchronize unmigrated apps: bootstrap3
      Apply all migrations: project, activity, zinnia, sessions, auth, badge, admin, coupon, contenttypes, sites
    Synchronizing apps without migrations:
      Creating tables...
      Installing custom SQL...
      Installing indexes...
    Running migrations: Applying zinnia.0001_initial...Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 161, in handle
        executor.migrate(targets, plan, fake=options.get("fake", False))
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/db/migrations/executor.py", line 68, in migrate
        self.apply_migration(migration, fake=fake)
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
        if self.detect_soft_applied(migration):
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
        apps = project_state.render()
      File "/home/username/.virtualenvs/project/local/lib/python3.4/site-packages/django/db/migrations/state.py", line 75, in render
        "for more" % new_unrendered_models
    django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'zinnia.Author'>]
    This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
     in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more

**Comment by argaen** [comment]
Samer error here with django==1.7.5 and django-blog-zinnia==0.15.1

**Comment by Fantomas42** [comment]
@argaen do you have customized the User model ?

**Comment by aniav** [comment]
I have the same error with a customized User model on django==1.7.4 and django.blog.zinnia==0.15.1.

**Comment by faraggi** [comment]
Oh good, I thought I was the only one there for a moment.

@argaen, @aniav What are your user model customizations? (if any)
I've created a subclass of AbstractBaseUser in which I change some basic attributs like first_name and date_joined etc....
I also have a property decorator on the username function.

I can't seem to discover what is bugging the migration.

**Comment by aniav** [comment]
My user model has no username, only email as a username field. In my case the migration should have been faked as it turned out, because all the tables already existed - but I should now create a separate migration on my side that would change the foreign key constraint for zinnia blog author and set it on the new user model. My application was upgraded from Django 1.4 to 1.7 recently, that's why I had tables created earlier and had to fake migrations.

**Comment by argaen** [comment]
@Fantomas42 @faraggi Yeah, I have custom User model. It inherits from `AbstracUser` to add a couple of fields.

**Comment by RossLYoung** [comment]
Me too. From #400 , I added to the zinnia initial migration......

from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('sites', '0001_initial'),
        (migrations.swappable_dependency(settings.AUTH_USER_MODEL)),
    ]

The initial migration now works.

**Comment by pgcd** [comment]
Having the same problem (with custom user model), and @RossLYoung solution works for me.

**Comment by faraggi** [comment]
@RossLYoung @argaen @aniav Thanks RossLYoung, your solution also worked for me.

**Comment by argaen** [comment]
+1 here. @RossLYoung solution works.

**Comment by kcolton** [comment]
+1 - @RossLYoung solution worked for me. My workaround: created a copy of the migration, made @RossLYoung change and an entry in MIGRATION_MODULES like 'zinnia': 'ext.zinnia_migrations'

**Comment by harshaddevale-tudip** [comment]
Hi,
I am getting error for django-1.7.1 and python 2.7

This is the output i get when trying to migrate:
Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/venv/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/venv/local/lib/python2.7/site-packages/zinnia/models/__init__.py", line 5, in <module>
    from zinnia.models.author import Author
  File "/home/venv/local/lib/python2.7/site-packages/zinnia/models/author.py", line 22, in <module>
    class Author(get_user_model(),
  File "/home/venv/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 136, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/home/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/home/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
