### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by fvezzoli** [Fantomas42/django-blog-zinnia#388]
I try to install Zinnia but when syncdb I get an error, and I don't find solution:

>Traceback (most recent call last):
>  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 284, in execute
    self.validate()
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 310, in validate
    num_errors = get_validation_errors(s, app)
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/core/management/validation.py", line 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 196, in get_app_errors
    self._populate()
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 75, in _populate
    self.load_app(app_name, True)
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/zinnia/models/__init__.py", line 4, in <module>
    from zinnia.models.entry import Entry
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/zinnia/models/entry.py", line 6, in <module>
    class Entry(load_model_class(ENTRY_BASE_MODEL)):
  File "/srv/www/django/venv/local/lib/python2.7/site-packages/zinnia/models_bases/__init__.py", line 20, in load_model_class
    raise ImproperlyConfigured('%s cannot be imported' % model_path)
django.core.exceptions.ImproperlyConfigured: zinnia.models_bases.entry.AbstractEntry cannot be imported

**Comment by Fantomas42** [comment]
Zinnia 0.15 only works with django 1.7

**Comment by fvezzoli** [comment]
Ok, thanks.

**Comment by ilGuccio** [comment]
I have the same problem, with django 1.8.3 and zinnia 0.14.3

**Comment by ZuluPro** [comment]
@ilGuccio Zinnia doesn't support yet Django 1.8:
https://github.com/Fantomas42/django-blog-zinnia/issues/411
