### ISSUE TITLE
Import Error 

### ISSUE THREAD

**Issue by tilaprimera** [Fantomas42/django-blog-zinnia#399]
Followed the documentation, and the following are included in the installed apps.

    'django_comments',
    'mptt',
    'tagging',
    'zinnia',

And urls.py has been configured as

    url(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
    url(r'^comments/', include('django_comments.urls')),

I get the following exception! 

    raise ImproperlyConfigured('%s cannot be imported' % model_path)
    django.core.exceptions.ImproperlyConfigured: zinnia.models_bases.entry.AbstractEntry cannot be  
    imported

**Comment by Fantomas42** [comment]
Hello,

can you give the version of Python, Django and Zinnia used ?

This error is strange because zinnia.models_bases.entry.AbstractEntry is the default model provided.

Regards

**Comment by tilaprimera** [comment]
Django (1.6.10)
Python (2.7.8)
Zinnia(0.15.1)

Installed via,  pip install djang-blog-zinnia. Sorry the notifications were flooded, just saw this reply of yours and sending it in asap.

**Comment by Fantomas42** [comment]
Zinnia 0.15.1 works with Django 1.7
Either you use a more recent version of Django, or you use Zinnia v0.14.x

http://django-blog-zinnia.readthedocs.org/en/latest/notes/compatibility.html#compatibility-with-django

Regards

**Comment by chhantyal** [comment]
This is problem with 0.14.x

````
File "/Users/usr/project/buildout/eggs/Django-1.6.11-py2.7.egg/django/db/models/loading.py", line 99, in load_app
    models = import_module('%s.models' % app_name)
  File "/Users/usr/project/buildout/eggs/Django-1.6.11-py2.7.egg/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/usr/project/buildout/eggs/django_blog_zinnia-0.14.2-py2.7.egg/zinnia/models/__init__.py", line 4, in <module>
    from zinnia.models.entry import Entry
  File "/Users/usr/project/buildout/eggs/django_blog_zinnia-0.14.2-py2.7.egg/zinnia/models/entry.py", line 6, in <module>
    class Entry(load_model_class(ENTRY_BASE_MODEL)):
  File "/Users/usr/project/buildout/eggs/django_blog_zinnia-0.14.2-py2.7.egg/zinnia/models_bases/__init__.py", line 20, in load_model_class
    raise ImproperlyConfigured('%s cannot be imported' % model_path)
django.core.exceptions.ImproperlyConfigured: zinnia.models_bases.entry.AbstractEntry cannot be imported
````

**Comment by simod** [comment]
I get this error as well with django 1.6.x due to:
>>> import zinnia.models_bases.entry.AbstractEntry
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/zinnia/models_bases/entry.py", line 15, in <module>
    from tagging.fields import TagField
  File "/usr/local/lib/python2.7/dist-packages/tagging/fields.py", line 9, in <module>
    from tagging.models import Tag
  File "/usr/local/lib/python2.7/dist-packages/tagging/models.py", line 10, in <module>
    from django.contrib.contenttypes.fields import GenericForeignKey
ImportError: No module named fields

Thanks for any suggestion

**Comment by Fantomas42** [comment]
@simod I think your issue is coming from a too recent version of django-tagging.

Downgrade it and it will be fine.

**Comment by simod** [comment]
@Fantomas42 thanks! worked with django-tagging==0.3
