### ISSUE TITLE
Django 1.7 with new install problem

### ISSUE THREAD

**Issue by mrgaolei** [Fantomas42/django-blog-zinnia#417]
Django 1.7.7
zinnia 0.15.1

django-admin.py startproject
I begin to write a new project
and I only install zinnia on INSTALLED_APP
when I run ./manage.py migrate
it prompt:

Operations to perform:
  Synchronize unmigrated apps: zinnia, mptt, django_comments, tagging
  Apply all migrations: admin, contenttypes, sites, auth, sessions
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Django-1.7.7-py2.7.egg/django/db/migrations/state.py", line 75, in render
    "for more" % new_unrendered_models
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'zinnia.Author'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more

**Comment by Fantomas42** [comment]
Do you have customized the User model ?

**Comment by Fantomas42** [comment]
Seems that is the contenttype app which cause the issue, if I understand this line correctly...

 Applying contenttypes.0001_initial...Traceback (most recent call last):

Weird

**Comment by Fantomas42** [comment]
Can you paste me your setting file on friendpaste ?

**Comment by Fantomas42** [comment]
I just made a new install from scratch like you describe, and everything works fine !

**Comment by Fantomas42** [comment]
I close the issue until further information.
