### ISSUE TITLE
TypeError: unorderable types: Entry() < Entry()

### ISSUE THREAD

**Issue by itbabu** [Fantomas42/django-blog-zinnia#432]
Hello,
I'm getting an error and I'm still not able to reproduce it in my localhost, so I'll try dump my PostgreSQL production database and mount it locally.
I'm using python 3.4 and latest zinnia version.

Here the traceback:

```bash
Internal Server Error: /blog/2014/06/06/fatturazione-pa/
Traceback (most recent call last):
  File "/opt/website/lib/python3.4/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/opt/website/lib/python3.4/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/opt/website/lib/python3.4/site-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/opt/website/lib/python3.4/site-packages/sekizai/templatetags/sekizai_tags.py", line 79, in render_tag
    rendered_contents = nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/classytags/core.py", line 106, in render
    return self.render_tag(context, **kwargs)
  File "/opt/website/lib/python3.4/site-packages/cms/templatetags/cms_tags.py", line 673, in render_tag
    rendered_contents = nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/defaulttags.py", line 402, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 858, in render_node
    return node.render(context)
  File "/opt/website/lib/python3.4/site-packages/django/template/base.py", line 1207, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/opt/website/lib/python3.4/site-packages/zinnia/templatetags/zinnia.py", line 179, in get_similar_entries
    CACHE_ENTRIES_RELATED[key] = compute_related(object_id, dataset)
  File "/opt/website/lib/python3.4/site-packages/zinnia/templatetags/zinnia.py", line 172, in compute_related
    key=lambda k_v: (k_v[1], k_v[0]))
TypeError: unorderable types: Entry() < Entry()
```

**Comment by Fantomas42** [comment]
From the traceback, you are not using the development version.

Can you try to reproduce the issue with the develop version of Zinnia, since the module has been completely rewritten ?

Note I was not able to reproduce the issue before, that's why if you can provide datas I will be thankful.

Regards

**Comment by Fantomas42** [comment]
Okay I was able to reproduce the issue, which occurs only on Python 3.
The issue was fixed during the re factorization on the implicated module.

So if you use the develop version, this will fix the issue.

Regards

**Comment by itbabu** [comment]
Thanks.
I had 0.15.1
Today I moved to develop and the error disappeared.

Cheers
marco
