### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-8: ordinal not in range(128)

### ISSUE THREAD

**Issue by busla** [Fantomas42/django-blog-zinnia#438]
I´m getting the following error when using wp2zinnia. I´m able to import tags, categories and the first 4 posts before it crashes.

```python
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/zinnia_wordpress/management/commands/wp2zinnia.py", line 115, in handle_label
    self.import_entries(tree.findall('channel/item'))
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/zinnia_wordpress/management/commands/wp2zinnia.py", line 359, in import_entries
    self.write_out('> %s... ' % title)
  File "/opt/python/run/venv/local/lib/python3.4/site-packages/zinnia_wordpress/management/commands/wp2zinnia.py", line 87, in write_out
    sys.stdout.write(smart_str(message))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-8: ordinal not in range(128)
```

**Comment by Fantomas42** [comment]
Please open the issue on the right repository https://github.com/django-blog-zinnia/wordpress2zinnia/ and specify the versions used.
