### ISSUE TITLE
ProgrammingError at /admin/zinnia/entry/

### ISSUE THREAD

**Issue by scotontheedge** [Fantomas42/django-blog-zinnia#479]
Hi, 

Been trying to get zinnia to work with the latest version of Django (1.9) and hitting numerous problems. Here is the one I haven't been able to fix. Any ideas what is going on?

Internal Server Error: /admin/zinnia/entry/

ProgrammingError at /admin/zinnia/entry/
column "zinnia_category.title" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT DISTINCT "zinnia_category"."id", "zinnia_category"."t...
                                               ^

Request Method: GET
Request URL: http://127.0.0.1:8000/admin/zinnia/entry/
Django Version: 1.9.7
Python Executable: /Users/kennethmarritt/.virtualenvs/stickpin/bin/python
Python Version: 2.7.11
Python Path: ['/Users/kennethmarritt/stickpin', '/Users/kennethmarritt/.virtualenvs/stickpin/src/inflect', '/Users/kennethmarritt/.virtualenvs/stickpin/src/django-blog-zinnia', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python27.zip', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/plat-darwin', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/plat-mac', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/lib-tk', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/lib-old', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/lib-dynload', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages', '/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/newrelic-2.50.0.39']
Server time: Wed, 8 Jun 2016 15:10:38 +0000
Installed Applications:
(u'django.contrib.admin',
u'django.contrib.auth',
u'django.contrib.contenttypes',
u'django.contrib.sessions',
u'django.contrib.messages',
u'django.contrib.staticfiles',
u'django.contrib.sites',
u'django.contrib.sitemaps',
u'stickpin',
u'odds',
u'rest_framework',
u'details',
u'selections',
u'scraper',
u'heatmap',
u'betturtle',
u'unfriendly',
u'storages',
u'robots',
u'webmaster_verification',
u'ckeditor',
u'ckeditor_uploader',
u'django_ajax',
u'django_comments',
u'mptt',
u'tagging',
u'zinnia_bootstrap',
u'zinnia',
u'zinnia_twitter',
u'zinnia_ckeditor',
u'offers',
u'newsletter',
u'collectfast',
u'debug_toolbar',
u'debug_panel',
u'django_stormpath',
u'django_social_share')
Installed Middleware:
(u'htmlmin.middleware.MarkRequestMiddleware',
u'django.contrib.sessions.middleware.SessionMiddleware',
u'django.middleware.common.CommonMiddleware',
u'django.middleware.csrf.CsrfViewMiddleware',
u'django.contrib.auth.middleware.AuthenticationMiddleware',
u'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
u'django.contrib.messages.middleware.MessageMiddleware',
u'django.middleware.clickjacking.XFrameOptionsMiddleware',
u'django.middleware.security.SecurityMiddleware',
u'django_ajax.middleware.AJAXMiddleware')

Traceback:  

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
 149.                     response = self.process_exception_by_middleware(e, request)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
 147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/contrib/admin/options.py" in wrapper
 541.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
 149.                     response = view_func(request, *args, **kwargs)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
 57.         response = view_func(request, *args, **kwargs)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/contrib/admin/sites.py" in inner
 244.             return view(request, *args, **kwargs)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
 67.             return bound_func(*args, **kwargs)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapped_view
 149.                     response = view_func(request, *args, **kwargs)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
 63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/contrib/admin/options.py" in changelist_view
 1470.                 self.list_max_show_all, self.list_editable, self)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/contrib/admin/views/main.py" in __init__
 78.         self.queryset = self.get_queryset(request)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/contrib/admin/views/main.py" in get_queryset
 321.          filters_use_distinct) = self.get_filters(request)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/contrib/admin/views/main.py" in get_filters
 115.                         self.model, self.model_admin)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/contrib/admin/filters.py" in __init__
 77.         self.lookup_choices = list(lookup_choices)

File "/Users/kennethmarritt/.virtualenvs/stickpin/src/django-blog-zinnia/zinnia/admin/filters.py" in lookups
 26.         for active_object in active_objects:

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/db/models/query.py" in __iter__
 258.         self._fetch_all()

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/db/models/query.py" in _fetch_all
 1074.             self._result_cache = list(self.iterator())

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/db/models/query.py" in __iter__
 52.         results = compiler.execute_sql()

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql
 848.             cursor.execute(sql, params)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
 64.                 return self.cursor.execute(sql, params)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/db/utils.py" in __exit__
 95.                 six.reraise(dj_exc_type, dj_exc_value, traceback)

File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
 64.                 return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /admin/zinnia/entry/
Exception Value: column "zinnia_category.title" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT DISTINCT "zinnia_category"."id", "zinnia_category"."t...

**Comment by Fantomas42** [comment]
> Been trying to get zinnia to work with the latest version of Django (1.9) and hitting numerous problems. Here is the one I haven't been able to fix. Any ideas what is going on?

I have no ideas... It's the first time I see this type of error...
But when you say "hitting numerous problems", what kind of problems do you talk ? Because I don't encounter problems, and I'm curious.

Regards

**Comment by scotontheedge** [comment]
On Django 1.8.12 I have Zinnia Blog working perfectly. I then upgrade to Django 1.9 and get the error above when attempting to load the blog. This is the problem I am trying to overcome.

I have tried various combinations of uninstalling the database tables, re-running migrations, Django settings (as per the Zinnia documentation), but not worked.

Thanks.

**Comment by Fantomas42** [comment]
What version of Zinnia do you use ?

**Comment by scotontheedge** [comment]
Hi. The version that works for me on Django 1.8.12 is 0.16.dev0.

I have tried to upgrade to Zinnia 0.17 and get the following error:

Internal Server Error: /blog/
Traceback (most recent call last):
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
   response = response.render()
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/response.py", line 158, in render
   self.content = self.rendered_content
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
   content = template.render(context, self._request)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
   return self.template.render(context)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 210, in render
   return self._render(context)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
   return self.nodelist.render(context)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 905, in render
   bit = self.render_node(node, context)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 919, in render_node
   return node.render(context)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/loader_tags.py", line 113, in render
   compiled_parent = self.get_parent(context)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/loader_tags.py", line 110, in get_parent
   return context.template.engine.get_template(parent)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/engine.py", line 167, in get_template
   template, origin = self.find_template(template_name, dirs)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/engine.py", line 141, in find_template
   source, display_name = loader(name, dirs)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/loaders/base.py", line 13, in __call__
   return self.load_template(template_name, template_dirs)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/loaders/base.py", line 23, in load_template
   template = Template(source, origin, template_name, self.engine)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 191, in __init__
   self.nodelist = engine.compile_string(template_string, origin)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/engine.py", line 261, in compile_string
   return parser.parse()
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
   compiled_result = compile_func(self, token)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/loader_tags.py", line 210, in do_extends
   nodelist = parser.parse()
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
   compiled_result = compile_func(self, token)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
   nodelist = parser.parse(('endblock',))
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
   compiled_result = compile_func(self, token)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/loader_tags.py", line 184, in do_block
   nodelist = parser.parse(('endblock',))
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
   compiled_result = compile_func(self, token)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/defaulttags.py", line 872, in do_for
   nodelist_loop = parser.parse(('empty', 'endfor',))
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 342, in parse
   compiled_result = compile_func(self, token)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 1096, in generic_tag_compiler
   defaults, takes_context, name)
 File "/Users/kennethmarritt/.virtualenvs/stickpin/lib/python2.7/site-packages/django/template/base.py", line 1076, in parse_bits
   name)
TemplateSyntaxError: 'zinnia_loop_template' received too many positional arguments

**Comment by Fantomas42** [comment]
With the version 0.17 everything should work fine.
But for your errors, you have to edit your customized template entry_list.html to adapt.

**Comment by patroqueeet** [comment]
same problem to me. django 1.8.0, zinnia 0.17. I have to idea how to fix that...

**Comment by patroqueeet** [comment]
solved by downgrade to 0.16. Please check http://stackoverflow.com/questions/26444452/simple-tag-as-variable-in-template - can be that 0.17 is not compatible with Django < 1.9

**Comment by Fantomas42** [comment]
Yes like described in the documentation, 0.17 is not compatiable with Django < 1.9.
