### ISSUE TITLE
(help) I follow the installation section of the docs,but got an error when I run the project.

### ISSUE THREAD

**Issue by zmrenwu** [Fantomas42/django-blog-zinnia#482]
I follow this docs: http://docs.django-blog-zinnia.com/en/develop/getting-started/install.html to start my project, everything were setted, but when I visit the index page, I got this error:

> FieldError at /weblog/
Cannot resolve keyword 'entries' into field. Choices are: comment_comments, comment_flags, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, user_permissions, username

and this is the traceback:

> Internal Server Error: /weblog/
Traceback (most recent call last):
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\core\handlers\base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\core\handlers\base.py", line 215, in _get_response
    response = response.render()
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\response.py", line 109, in render
    self.content = self.rendered_content
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\backends\django.py", line 66, in render
    return self.template.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 208, in render
    return self._render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 199, in _render
    return self.nodelist.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 994, in render
    bit = node.render_annotated(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\template\library.py", line 225, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\zinnia\templatetags\zinnia.py", line 84, in get_authors
    'authors': Author.published.all().annotate(
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\manager.py", line 160, in all
    return self.get_queryset()
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\zinnia\managers.py", line 107, in get_queryset
    entries__sites=Site.objects.get_current()
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\query.py", line 794, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\query.py", line 812, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\sql\query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\sql\query.py", line 1247, in _add_q
    current_negated, allow_joins, split_subq)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\sql\query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\sql\query.py", line 1133, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\sql\query.py", line 1019, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "D:\Users\zmrenwu\Envs\zinnia_env\lib\site-packages\django\db\models\sql\query.py", line 1327, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'entries' into field. Choices are: comment_comments, comment_flags, date_joined, email, first_name, groups, id, is_active, is_staff, is_superuser, last_login, last_name, logentry, password, user_permissions, username
[24/Aug/2016 16:44:13] "GET /weblog/ HTTP/1.1" 500 248632

How to fix it? With this error I can't publish any entry. But I can create other items in admin.

**Comment by zmrenwu** [comment]
All right, I solved it! Becuase I use django 1.10, maybe zinnia still not support it. Thank you for develop such excellent app. I'll use it to build my blog and hope I can make some contributions to it. This issue can be closed.

**Comment by bittner** [comment]
@zmrenwu You can/must close this issue yourself.

**Comment by josephshirima** [comment]
@zmrenwu  could you please explain how you manage to get out from that error! Because am experience the same error right now! please help i install zinnia with pip install django-blog-zinnia and it seem it install all dependence itself.

Collecting Django>=1.7 (from django-contrib-comments>=1.6.0->django-blog-zinnia)
  Using cached Django-1.10-py2.py3-none-any.whl

it picked django-1.10

**Comment by bittner** [comment]
@josephshirima Sounds like you have to install django-blog-zinnia version 1.9.x.

## Analysis

- According to @zmrenwu's comment above this is a compatibility issue with Django 1.10.
- [According to the Zinnia docs](http://django-blog-zinnia.readthedocs.io/en/develop/notes/compatibility.html) Zinnia 0.17 is incompatible with Django 1.8.x.

Hence, you must stick with Django 1.9.x if you install Zinnia 0.17 (the current release). - Same story for older versions of Zinnia, as noted in the Zinnia docs compatibility chapter (link above).

## What to do (Example for Zinnia 0.17) 

Add this to your `requirements.txt` (and run `pip install -r requirements.txt`):
``` bash
# -- content of: requirements.txt
django-blog-zinnia>=1.9,<1.10
```
or run the following command to install the right version of Django for a single time:
``` bash
pip install "django-blog-zinnia>=1.9,<1.10"
```
The syntax might be different on Windows.

**Comment by josephshirima** [comment]
Thank you @bittner i have manage to make things work from your solution.. Thanx much brother!

**Comment by bittner** [comment]
@josephshirima You're welcome, Joseph!

@zmrenwu Can you please press the "Close issue" button here in this issue?

**Comment by Fantomas42** [comment]
Just a note about Django 1.10, I'm currently working on it.
Excepting an issue in the admin interface, I have not encountered the error described.

Strange...
