### ISSUE TITLE
ValueError: too many values to unpack when accessing entry via admin

### ISSUE THREAD

**Issue by stefko18** [Fantomas42/django-blog-zinnia#512]
# Actual behavior
I created one entry in the admin and when i tried to change it i couldn't anymore. I can view the entry as a user on the page, but i can not create new entries nor edit the created. see below the traceback (form which I can't get any useful information what happend):

# Expected behavior
Just tryng to change the created entry or creating a new one in the admin.

# Steps to reproduce the issue

No idea what happend. I created one entry and tried to change it. Don't understand this.

# Specifications

 - Zinnia version: 0.18.1
 - Django version: 1.11.2
 - Python version: 2.7
 - Operating system: Ubuntu

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [x] I have read the guidelines for contributing linked to above.
 - [x] I have checked for duplicate issues.
 - [x] This is not a support request.

  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/ubuntu/workspace/project/apps/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/workspace/project/apps/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/ubuntu/workspace/project/apps/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/ubuntu/workspace/project/apps/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/ubuntu/workspace/project/apps/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/loader_tags.py", line 216, in render
    return template.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 209, in render
    return self._render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/defaulttags.py", line 216, in render
    nodelist.append(node.render_annotated(context))
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/home/ubuntu/workspace/project/apps/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/home/ubuntu/workspace/project/apps/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/home/ubuntu/workspace/project/apps/django/utils/html.py", line 376, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/home/ubuntu/workspace/project/apps/django/forms/boundfield.py", line 41, in __str__
    return self.as_widget()
  File "/home/ubuntu/workspace/project/apps/django/forms/boundfield.py", line 127, in as_widget
    **kwargs
  File "/home/ubuntu/workspace/project/apps/django/forms/widgets.py", line 220, in render
    context = self.get_context(name, value, attrs)
  File "/home/ubuntu/workspace/project/apps/django/contrib/admin/widgets.py", line 281, in get_context
    'rendered_widget': self.widget.render(name, value, attrs),
  File "/home/ubuntu/workspace/project/apps/django/forms/widgets.py", line 220, in render
    context = self.get_context(name, value, attrs)
  File "/home/ubuntu/workspace/project/apps/django/contrib/admin/widgets.py", line 38, in get_context
    context = super(FilteredSelectMultiple, self).get_context(name, value, attrs)
  File "/home/ubuntu/workspace/project/apps/django/forms/widgets.py", line 667, in get_context
    context = super(Select, self).get_context(name, value, attrs)
  File "/home/ubuntu/workspace/project/apps/django/forms/widgets.py", line 629, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/home/ubuntu/workspace/project/apps/django/forms/widgets.py", line 577, in optgroups
    for index, (option_value, option_label) in enumerate(chain(self.choices)):
ValueError: too many values to unpack

Also I found the forms modules in django that started to throw this error and placed a print in it, here is what I got:

    def optgroups(self, name, value, attrs=None):
        """Return a list of optgroups for this widget."""
        groups = []
        has_selected = False
        print "name",name
        print "value",value
        print "attrs",attrs
        print self.choices

        for index, (option_value, option_label) in enumerate(chain(self.choices)):
            if option_value is None:
                option_value = ''

            subgroup = []
            if isinstance(option_label, (list, tuple)):
                group_name = option_value
                subindex = 0
                choices = option_label
            else:
                group_name = None
                subindex = None
                choices = [(option_value, option_label)]
            groups.append((group_name, subgroup, index))

            for subvalue, sublabel in choices:
                selected = (
                    force_text(subvalue) in value and
                    (has_selected is False or self.allow_multiple_selected)
                )
                if selected is True and has_selected is False:
                    has_selected = True
                subgroup.append(self.create_option(
                    name, subvalue, sublabel, selected, index,
                    subindex=subindex, attrs=attrs,
                ))
                if subindex is not None:
                    subindex += 1
        return groups
----------------------------
value [u'0']
attrs {u'id': u'id_status'}
[(0, u'draft'), (1, u'hidden'), (2, u'published')]
name sites
value [u'2']
attrs {u'required': True, u'id': u'id_sites'}
<django.forms.models.ModelChoiceIterator object at 0x7f0980bf5450>
name content_template
value [u'zinnia/_entry_detail.html']
attrs {u'required': True, u'id': u'id_content_template'}
[('zinnia/_entry_detail.html', u'Default template')]
name detail_template
value [u'entry_detail.html']
attrs {u'required': True, u'id': u'id_detail_template'}
[('entry_detail.html', u'Default template')]
name authors
value [u'66']
attrs {u'id': u'id_authors'}
<django.forms.models.ModelChoiceIterator object at 0x7f0980bf5f10>
name related
value [u'']
attrs {u'id': u'id_related'}
<django.forms.models.ModelChoiceIterator object at 0x7f0980b7d150>
name categories
value [u'']
attrs {u'id': u'id_categories'}
<zinnia.admin.fields.MPTTModelChoiceIterator object at 0x7f0980b7d310>
Traceback (most recent call last): and here comes the error traceback

EDIT: I reinstalled the whole package and the issue persists ... 

EDIT2:
Another couple of trys in File "/home/ubuntu/workspace/project/apps/django/forms/widgets.py", line 577, in optgroups, iadded this to see values:

    def optgroups(self, name, value, attrs=None):
        """Return a list of optgroups for this widget."""
        groups = []
        has_selected = False
        print name
        print value
        print attrs
        
        try:
            print enumerate(chain(self.choices))
        except:
            print enumerate(chain(self.choices.items()))

        for item in enumerate(chain(self.choices)):
            print item

        for index, (option_value, option_label) in enumerate(chain(self.choices)):

And these are the results:

related
[]
{u'id': u'id_related'}
<enumerate object at 0x7f32eea2adc0>
(0, (2, u'fff: published'))
categories
[]
{u'id': u'id_categories'}
<enumerate object at 0x7f32eea2ad70>
(0, (1, u'Test123', (1, 1)))

Obviously it breaks beacuse of categories. My category Test123 does for some reason arrive with four values instead of the expected three. Once I deleted the category everything started to workout fine. I still consider this a zinnia bug. I currently can not use Categories because they break the entry admin.

**Comment by ThuwarakeshM** [comment]
I have the same issue. However, I also noticed that we can add, edit, delete entries as long as we do not have any categories in the db. That is, the problem arises only we add categories. 

The below is my stack trace:

`Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/zinnia/entry/3/change/

Django Version: 1.11.2
Python Version: 3.5.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.facebook',
 'allauth.socialaccount.providers.google',
 'django_comments',
 'mptt',
 'tagging',
 'zinnia']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']


Template error:
In template /home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19
   too many values to unpack (expected 2)   9 :             {% for field in line %}
   10 :                 <div{% if not line.fields|length_is:'1' %} class="field-box{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}"{% elif field.is_checkbox %} class="checkbox-row"{% endif %}>
   11 :                     {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
   12 :                     {% if field.is_checkbox %}
   13 :                         {{ field.field }}{{ field.label_tag }}
   14 :                     {% else %}
   15 :                         {{ field.label_tag }}
   16 :                         {% if field.is_readonly %}
   17 :                             <div class="readonly">{{ field.contents }}</div>
   18 :                         {% else %}
   19 :                              {{ field.field }} 
   20 :                         {% endif %}
   21 :                     {% endif %}
   22 :                     {% if field.field.help_text %}
   23 :                         <div class="help">{{ field.field.help_text|safe }}</div>
   24 :                     {% endif %}
   25 :                 </div>
   26 :             {% endfor %}
   27 :         </div>
   28 :     {% endfor %}
   29 : </fieldset>


Traceback:

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/response.py" in render
  107.             self.content = self.rendered_content

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/response.py" in rendered_content
  84.         content = template.render(context, self._request)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/backends/django.py" in render
  66.             return self.template.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  207.                     return self._render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  177.             return compiled_parent._render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  72.                 result = block.nodelist.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  72.                 result = block.nodelist.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  216.                     nodelist.append(node.render_annotated(context))

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  216.                 return template.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  209.                 return self._render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  216.                     nodelist.append(node.render_annotated(context))

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  216.                     nodelist.append(node.render_annotated(context))

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  322.                 return nodelist.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  322.                 return nodelist.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  990.                 bit = node.render_annotated(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  957.             return self.render(context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render
  1046.         return render_value_in_context(output, context)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/template/base.py" in render_value_in_context
  1024.     value = force_text(value)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/utils/encoding.py" in force_text
  76.                     s = six.text_type(s)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/utils/html.py" in <lambda>
  385.         klass.__str__ = lambda self: mark_safe(klass_str(self))

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/forms/boundfield.py" in __str__
  41.         return self.as_widget()

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/forms/boundfield.py" in as_widget
  127.             **kwargs

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/forms/widgets.py" in render
  220.         context = self.get_context(name, value, attrs)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/contrib/admin/widgets.py" in get_context
  281.             'rendered_widget': self.widget.render(name, value, attrs),

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/forms/widgets.py" in render
  220.         context = self.get_context(name, value, attrs)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/contrib/admin/widgets.py" in get_context
  38.         context = super(FilteredSelectMultiple, self).get_context(name, value, attrs)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/forms/widgets.py" in get_context
  663.         context = super(Select, self).get_context(name, value, attrs)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/forms/widgets.py" in get_context
  625.         context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)

File "/home/thuwarakesh/projects/demo/lib/python3.5/site-packages/django/forms/widgets.py" in optgroups
  573.         for index, (option_value, option_label) in enumerate(chain(self.choices)):

Exception Type: ValueError at /admin/zinnia/entry/3/change/
Exception Value: too many values to unpack (expected 2)
`

**Comment by raylight75** [comment]
I have the same issue too

**Comment by raylight75** [comment]
For now i'm downgraded to Django 1.10.7 and everything working fine

**Comment by mikebader** [comment]
The problem appears to be how Django 1.11 receives the value of the `MPTTModelMultipleChoiceField` choices that returns a tuple of left and right sort values to implement MPTT in addition to the choice and its label (that is the extra `(1,1)` returned when stefko18 enumerated the values of `id_categories). 

If you comment out the following lines 56-60 in zinnia/admin/forms.py, the admin interface works (albeit without MPTT), i.e.: 

    class EntryAdminForm(forms.ModelForm):
        """
        Form for Entry's Admin.
        """
    #     categories = MPTTModelMultipleChoiceField(
    #         label=_('Categories'), required=False,
    #         queryset=Category.objects.all(),
    #         widget=MPTTFilteredSelectMultiple(_('categories'))
    #         )

**Comment by stefko18** [comment]
Thanks @mikebader  this is a great temporary fix. Not sure what the lines do that I commented out, but finally I can use categories. Nice. I hope there will be a permanent fix someday.

**Comment by eSanFX** [comment]
For me, I have identified the problem code as being in method choice() of class MPTTModelChoiceIterator within the module zinnia/admin/fields.py.

The zinnia code overloads the choice method of ModelChoiceIterator from django.forms.models. Unfortunately this overload returns a tuple that django chokes on.

Specifically, this next line seems wrong:

   ` return super(MPTTModelChoiceIterator, self).choice(obj) + ((tree_id, left),)`

A better solution would be something like:
```
    choice = super(MPTTModelChoiceIterator, self).choice(obj)
    return choice (choice[:1] + (tree_id, left),), choice[1]
```
Note the sorting information should be grouped into the first inner tuple. Making this change to the source worked for me but I have not extensively tested it. Hope it helps someone.

**Comment by HenrikEckermann** [comment]
Same problem here. But as in the documentation of zinnia is stated: It is not yet for Django 1.11. I gave it a try still and ended where you also ended. The outcommenting does not prevent the error for me. I have to avoid categories.

Does anybody know if zinnia will be updated so that it will get compatible with Django 1.11? If this happens soon I would not change to 1.10 but instead edit categories later....

**Comment by igorkurochka** [comment]
Same error even using Django 1.10.7
after I added a category I can't add new blog entry anymore. For the moment I just won't be using categories.

**Comment by igorkurochka** [comment]
@Admoroux thanks for the info, but I don't like the idea to change code installed from pip. 
hope @Fantomas42 will release update with the fix soon

**Comment by Admoroux** [comment]
Me neither, @igorkurochka, but for testing I didn't install it from pip, but downloaded as zip to a local folder inside my project just to check it up. I hope update it soon too...
(Excuse my english, I'm from Spain)

**Comment by RobertoMaurizzi** [comment]
Not sure if you're still interested 😅 but I needed this MPTTModelMultipleChoiceField for a project we're working on (still on Django 1.11) and got the same error. It turns out it's enough to override the optgroups method with one that doesn't choke on the extra tuple added by MPTTModelChoiceIterator.

copypaste:
```
from itertools import chain
from django import forms
from django.contrib.admin import widgets
from django.utils.encoding import smart_unicode, force_unicode, force_text
from django.utils.html import escape, conditional_escape


class MPTTModelChoiceIterator(forms.models.ModelChoiceIterator):
    """MPTT version of ModelChoiceIterator"""
    def choice(self, obj):
        """Overriding choice method"""
        tree_id = getattr(obj, self.queryset.model._mptt_meta.tree_id_attr, 0)
        left = getattr(obj, self.queryset.model._mptt_meta.left_attr, 0)
        return super(MPTTModelChoiceIterator,
                     self).choice(obj) + ((tree_id, left),)


class MPTTModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    """MPTT version of ModelMultipleChoiceField"""
    def __init__(self, *args, **kwargs):
        self.level_indicator = kwargs.pop('level_indicator', '+--')
        super(MPTTModelMultipleChoiceField, self).__init__(*args, **kwargs)

    def label_from_instance(self, obj):
        """Creates labels which represent the tree level of each node
        when generating option labels."""
        return u'%s %s' % (self.level_indicator * getattr(
            obj, obj._mptt_meta.level_attr), smart_unicode(obj))

    def _get_choices(self):
        """Overriding _get_choices"""
        if hasattr(self, '_choices'):
            return self._choices
        return MPTTModelChoiceIterator(self)

    choices = property(_get_choices, forms.ChoiceField._set_choices)


class MPTTFilteredSelectMultiple(widgets.FilteredSelectMultiple):
    """MPTT version of FilteredSelectMultiple"""
    def render_options(self, choices, selected_choices):
        """
        This is copy'n'pasted from django.forms.widgets Select(Widget)
        change to the for loop and render_option so they will unpack
        and use our extra tuple of mptt sort fields (if you pass in
        some default choices for this field, make sure they have the
        extra tuple too!)
        """
        def render_option(option_value, option_label, sort_fields):
            """Inner scope render_option"""
            option_value = force_unicode(option_value)
            selected_html = (option_value in selected_choices) \
                and u' selected="selected"' or ''
            return u'<option value="%s" data-tree-id="%s" ' \
                   'data-left-value="%s"%s>%s</option>' % (
                       escape(option_value),
                       sort_fields[0],
                       sort_fields[1],
                       selected_html,
                       conditional_escape(force_unicode(option_label)),
                   )
        # Normalize to strings.
        selected_choices = set([force_unicode(v) for v in selected_choices])
        output = []
        for option_value, option_label, sort_fields in chain(
                self.choices, choices):
            if isinstance(option_label, (list, tuple)):
                output.append(u'<optgroup label="%s">' % escape(
                    force_unicode(option_value)))
                for option in option_label:
                    output.append(render_option(*option))
                output.append(u'</optgroup>')
            else:
                output.append(render_option(option_value, option_label,
                                            sort_fields))
        return u'\n'.join(output)

    def optgroups(self, name, value, attrs=None):
        """Return a list of optgroups for this widget.

        Adapted from django.forms.widgets.ChoiceWidget.optgroups method, the only change was
        adding `(t, p)` in the for loop"""
        groups = []
        has_selected = False

        for index, (option_value, option_label, (t, l)) in enumerate(chain(self.choices)):
            if option_value is None:
                option_value = ''

            subgroup = []
            if isinstance(option_label, (list, tuple)):
                group_name = option_value
                subindex = 0
                choices = option_label
            else:
                group_name = None
                subindex = None
                choices = [(option_value, option_label)]
            groups.append((group_name, subgroup, index))

            for subvalue, sublabel in choices:
                selected = (
                    force_text(subvalue) in value and
                    (has_selected is False or self.allow_multiple_selected)
                )
                if selected is True and has_selected is False:
                    has_selected = True
                subgroup.append(self.create_option(
                    name, subvalue, sublabel, selected, index,
                    subindex=subindex, attrs=attrs,
                ))
                if subindex is not None:
                    subindex += 1
        return groups

    class Media:
        # extend = False
        js = ("admin/js/core.js",
              "js/mptt_m2m_selectbox.js",
              "admin/js/SelectFilter2.js",)
```
