### ISSUE TITLE
Error rendering MPTT categories

### ISSUE THREAD

**Issue by benjaoming** [Fantomas42/django-blog-zinnia#522]
# Actual behavior

Loading the change form in django admin crashes with an exception:

```
Internal Server Error: /da/admin/zinnia/entry/111/change/
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "django/template/base.py", line 208, in render
    return self._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "django/template/base.py", line 210, in render
    return self._render(context)
  File "django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 510, in render
    return self.nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 392, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "django/template/base.py", line 1050, in render
    return render_value_in_context(output, context)
  File "django/template/base.py", line 1028, in render_value_in_context
    value = force_text(value)
  File "django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "django/utils/html.py", line 391, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "django/forms/boundfield.py", line 43, in __str__
    return self.as_widget()
  File "django/forms/boundfield.py", line 101, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "django/contrib/admin/widgets.py", line 307, in render
    'widget': self.widget.render(name, value, *args, **kwargs),
  File "django/contrib/admin/widgets.py", line 49, in render
    output = super(FilteredSelectMultiple, self).render(name, value, attrs)
  File "django/forms/widgets.py", line 626, in render
    options = self.render_options(value)
  File "django/forms/widgets.py", line 576, in render_options
    for option_value, option_label in self.choices:
ValueError: too many values to unpack (expected 2)
```

# Possible fix

Do not »*Overload the choice method to add the position of the object in the tree for future sorting.*«, just leave as is:

```
class MPTTModelChoiceIterator(forms.models.ModelChoiceIterator):
    """
    MPTT version of ModelChoiceIterator.
    """

    def choice(self, obj):
        """
        Overloads the choice method to add the position
        of the object in the tree for future sorting.
        """
        tree_id = getattr(obj, self.queryset.model._mptt_meta.tree_id_attr, 0)
        left = getattr(obj, self.queryset.model._mptt_meta.left_attr, 0)
        return super(MPTTModelChoiceIterator,
                     self).choice(obj)

```

# Expected behavior

No crash

# Steps to reproduce the issue

  1. You need to have categories
  2. Navigate to the change/create of an entry

# Specifications

 - Zinnia version: 0.19
 - django-mptt==0.8.7
 - Django version: 1.10
 - Python version: 3
 - Operating system: Ubuntu Xenial

# Disclaimer

Please read these questions **carefully** and answer honestly with an `x`
into all the boxes `[ ]`:

 - [x] I have read the guidelines for contributing linked to above.
 - [x] I have checked for duplicate issues.
 - [x] This is not a support request.

**Comment by Fantomas42** [comment]
Hello,

you should use Django 1.11 because Zinnia v0.19 is dedicated for this version of Django.

Use the 0.18 if you are stuck to Django 1.10

Regards
