### ISSUE TITLE
ImportError: cannot import name 'HTMLCalendar'

### ISSUE THREAD

**Issue by 995199148** [Fantomas42/django-blog-zinnia#530]
[root@test zinnia]# python managers.py migrate
Traceback (most recent call last):
  File "managers.py", line 2, in <module>
    from django.contrib.sites.models import Site
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/contrib/sites/models.py", line 4, in <module>
    from django.db import models
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/db/models/__init__.py", line 3, in <module>
    from django.db.models.aggregates import *  # NOQA
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/db/models/aggregates.py", line 5, in <module>
    from django.db.models.expressions import Case, Func, Star, When
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/db/models/expressions.py", line 7, in <module>
    from django.db.models import fields
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/db/models/fields/__init__.py", line 11, in <module>
    from django import forms
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/forms/__init__.py", line 6, in <module>
    from django.forms.boundfield import *  # NOQA
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/forms/boundfield.py", line 4, in <module>
    from django.forms.utils import flatatt, pretty_name
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/forms/utils.py", line 7, in <module>
    from django.utils.html import escape, format_html, format_html_join, html_safe
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/utils/html.py", line 10, in <module>
    from django.utils.http import RFC3986_GENDELIMS, RFC3986_SUBDELIMS
  File "/usr/local/python36/lib/python3.6/site-packages/Django-2.0.1-py3.6.egg/django/utils/http.py", line 2, in <module>
    import calendar
  File "/root/zhangpanfeng/django-blog-zinnia/zinnia/calendar.py", line 4, in <module>
    from zinnia.calendar import HTMLCalendar
  File "/usr/local/python36/lib/python3.6/site-packages/django_blog_zinnia-0.19.1.dev0-py3.6.egg/zinnia/calendar.py", line 4, in <module>
    from calendar import HTMLCalendar
ImportError: cannot import name 'HTMLCalendar'

**Comment by Fantomas42** [comment]
Irreproductible, does not follow guidelines. Close issue.
