### ISSUE TITLE
error rendering main page,cause column zinnia_entry.publication_date does not exist LINE 1: SELECT DISTINCT DATE_TRUNC('year', "zinnia_entry"."publicati... error

### ISSUE THREAD

**Issue by schopra6** [Fantomas42/django-blog-zinnia#534]
# Actual behavior
Installed zinnia  to my django webapp .It runs fine on my local machine but when i hosted it on heroku and opened the link to the blog,It showed this exception.

`2018-03-27T20:56:12.638992+00:00 app[web.1]: Internal Server Error: /weblog/
2018-03-27T20:56:12.639010+00:00 app[web.1]: Traceback (most recent call last):
2018-03-27T20:56:12.639013+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
2018-03-27T20:56:12.639014+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2018-03-27T20:56:12.639016+00:00 app[web.1]: psycopg2.ProgrammingError: column zinnia_entry.publication_date does not exist
2018-03-27T20:56:12.639018+00:00 app[web.1]: LINE 1: SELECT DISTINCT DATE_TRUNC('year', "zinnia_entry"."publicati...
2018-03-27T20:56:12.639020+00:00 app[web.1]:                                            ^
2018-03-27T20:56:12.639022+00:00 app[web.1]: 
2018-03-27T20:56:12.639025+00:00 app[web.1]: The above exception was the direct cause of the following exception:
2018-03-27T20:56:12.639023+00:00 app[web.1]: 
2018-03-27T20:56:12.639027+00:00 app[web.1]: 
2018-03-27T20:56:12.639029+00:00 app[web.1]: Traceback (most recent call last):
2018-03-27T20:56:12.639030+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
2018-03-27T20:56:12.639032+00:00 app[web.1]:     response = get_response(request)
2018-03-27T20:56:12.639034+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
2018-03-27T20:56:12.639036+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2018-03-27T20:56:12.639037+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
2018-03-27T20:56:12.639039+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2018-03-27T20:56:12.639041+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
2018-03-27T20:56:12.639042+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2018-03-27T20:56:12.639044+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
2018-03-27T20:56:12.639045+00:00 app[web.1]:     return handler(request, *args, **kwargs)
2018-03-27T20:56:12.639047+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/dates.py", line 339, in get
2018-03-27T20:56:12.639049+00:00 app[web.1]:     self.date_list, self.object_list, extra_context = self.get_dated_items()
2018-03-27T20:56:12.639050+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/dates.py", line 425, in get_dated_items
2018-03-27T20:56:12.639052+00:00 app[web.1]:     date_list = self.get_date_list(qs, ordering='DESC')
2018-03-27T20:56:12.639053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/views/generic/dates.py", line 404, in get_date_list
2018-03-27T20:56:12.639055+00:00 app[web.1]:     if date_list is not None and not date_list and not allow_empty:
2018-03-27T20:56:12.639057+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __bool__
2018-03-27T20:56:12.639058+00:00 app[web.1]:     self._fetch_all()
2018-03-27T20:56:12.639060+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 1102, in _fetch_all
2018-03-27T20:56:12.639061+00:00 app[web.1]:     self._result_cache = list(self._iterable_class(self))
2018-03-27T20:56:12.639063+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/query.py", line 152, in __iter__
2018-03-27T20:56:12.639064+00:00 app[web.1]:     for row in compiler.results_iter():
2018-03-27T20:56:12.639066+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 828, in results_iter
2018-03-27T20:56:12.639067+00:00 app[web.1]:     results = self.execute_sql(MULTI)
2018-03-27T20:56:12.639069+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
2018-03-27T20:56:12.639071+00:00 app[web.1]:     cursor.execute(sql, params)
2018-03-27T20:56:12.639072+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
2018-03-27T20:56:12.639074+00:00 app[web.1]:     return super(CursorDebugWrapper, self).execute(sql, params)
2018-03-27T20:56:12.639075+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
2018-03-27T20:56:12.639077+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2018-03-27T20:56:12.639078+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
2018-03-27T20:56:12.639080+00:00 app[web.1]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
2018-03-27T20:56:12.639081+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
2018-03-27T20:56:12.639083+00:00 app[web.1]:     raise value.with_traceback(tb)
2018-03-27T20:56:12.639085+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
2018-03-27T20:56:12.639086+00:00 app[web.1]:     return self.cursor.execute(sql, params)
2018-03-27T20:56:12.639090+00:00 app[web.1]: LINE 1: SELECT DISTINCT DATE_TRUNC('year', "zinnia_entry"."publicati...
2018-03-27T20:56:12.824826+00:00 app[web.1]: 10.136.187.237 - - [28/Mar/2018:02:26:12 +0530] "GET /weblog/ HTTP/1.1" 500 133513 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/64.0.3282.167 Chrome/64.0.3282.167 Safari/537.36"
2018-03-27T20:56:12.639092+00:00 app[web.1]:                                            ^
2018-03-27T20:56:12.639099+00:00 app[web.1]: 
2018-03-27T20:56:12.639088+00:00 app[web.1]: django.db.utils.ProgrammingError: column zinnia_entry.publication_date does not exist
2018-03-27T20:56:12.831728+00:00 heroku[router]: at=info method=GET path="/weblog/" host=blooming-headland-11176.herokuapp.com request_id=67cbd1e4-80b8-4de0-a962-21fd7305ef1f fwd="103.211.18.64" dyno=web.1 connect=1ms service=202ms status=500 bytes=133724 protocol=https
`

# Expected behavior
It should not raise such exception.

# Steps to reproduce the issue

  1.Add zinnia to settings.INSTALLED_APPS
  2.push source code on heroku and open the url link.
  

# Specifications

 - Zinnia version:0.20
 - Django version:1.11
 - Python version:3.5
 - Operating system:ubuntu 16.04

# Disclaimer

Before submitting an *issue* make sure you have:

 - [ X] Read the guidelines for contributing.
 - [ X] Checked for duplicate issues.
 - [ X] Not a support request.

**Comment by schopra6** [comment]
Deleted the migration python files
and then some series of steps
