### ISSUE TITLE
Unable build following installation instructuins

### ISSUE THREAD

**Issue by qagonpro** [Fantomas42/django-blog-zinnia#567]
(zinnie) C:\Users\Dagon\zinnie>manage.py check
Traceback (most recent call last):
  File "C:\Users\Dagon\zinnie\manage.py", line 21, in <module>
    main()
  File "C:\Users\Dagon\zinnie\manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Dagon\PycharmProjects\zinnie\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_co
mmand_line
    utility.execute()
  File "C:\Users\Dagon\PycharmProjects\zinnie\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\Dagon\PycharmProjects\zinnie\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Dagon\PycharmProjects\zinnie\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\Dagon\PycharmProjects\zinnie\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\Dagon\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Dagon\PycharmProjects\zinnie\lib\site-packages\zinnia\models\__init__.py", line 2, in <module>
    from zinnia.models.author import Author
  File "C:\Users\Dagon\PycharmProjects\zinnie\lib\site-packages\zinnia\models\author.py", line 6, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (C:\Users\Dagon\PycharmProjects\zinnie
\lib\site-packages\django\utils\encoding.py)

settings

# Actual behavior

# Expected behavior

# Steps to reproduce the issue

  1.
  2.
  3.

# Specifications

 - Zinnia version:
 - Django version:
 - Python version:
 - Operating system:

# Disclaimer

Before submitting an *issue* make sure you have:

 - [ ] Read the guidelines for contributing.
 - [ ] Checked for duplicate issues.
 - [ ] Not a support request.

**Comment by RduMarais** [comment]
**Same here, Got it to work!**
let me add a bit more information :

 * Django version : 3.0.6
 * Zinnia version : django-blog-zinnia-0.20
 * Python 3.7.6
 * OS : MacOS

By going throungh the commits, I found [the commit cb8283c](https://github.com/Fantomas42/django-blog-zinnia/commit/cb8283c39219b64bed4e2416c46c705f1368a8b1) that removes the cause of the error we have.

By installing the dev branch using `pip install git+https://github.com/Fantomas42/django-blog-zinnia.git` it worked

**Comment by Jonas-089** [comment]
I'm not very familiar with working with projects like this and git in general. Is this version stable/ "official"? If an update is made to the Zinnia, will this break the code again? I'm a bit scared of having something in my project that potentially screws up the entire website

**Comment by barneydesmond** [comment]
@Jonas-089 I'm currently assessing Zinnia to see if I can use it myself, and ran into this issue. The fix that RduMarais found above is in the "develop" git branch, which _can_ change over time.

However, if you use their method with `pip install` from github, and then never `pip upgrade` Zinnia, it won't break. You won't get any updates and improvements, but you won't get any breakages either. Note that if you upgrade your Django version, it may still break if Zinnia is incompatible with it.

**Comment by RduMarais** [comment]
> You won't get any updates and improvements, but you won't get any breakages either. 

real question : is this project really maintained ? I found a "xinnia" package on Pypi and I tend to have more and more compatibility issues

**Comment by elarroba** [comment]
@barneydesmond @Jonas-089 @RduMarais 

I just created a fork of this project and updated the code to work with modern versions of Django (including 4.0+). 

Please visit [https://github.com/arrobalytics/django-blog-zinnia](https://github.com/arrobalytics/django-blog-zinnia) if you want to contribute. Don't forget to star the project to show your support. 

Visit the new site [https://www.djangoblogzinnia.com](https://www.djangoblogzinnia.com) for documentation, demo and other resources.
